version: '3'
services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: svelte-components
    logging:
      driver: "none"
  cypress:
    image: "cypress/included:4.1.0"
    depends_on:
      - storybook
    working_dir: /tests
    volumes:
      - ./tests:/tests
